source "https://rubygems.org"

gemspec

gem "webmock", "~> 1.20.4"
gem "bundler", "~> 1.6"
gem "rake"
gem "rspec", "~> 3.0"
gem "rspec-rails", "~> 3.0"
gem "jquery-rails"
gem "capybara"
gem "pry"
gem "aws-sdk-v1"
gem "rack-test", "~> 0.6.2"
gem "rails", "~> 4.1.8"
gem "sqlite3"
gem "selenium-webdriver"
gem "yard"
gem "rubocop"
gem "redcarpet"
